### ISSUE TITLE
 Error: Cannot find module 'nlp-syllables'

### ISSUE THREAD

**Issue by factormystic** [nlp-compromise/nlp-syllables#1]
1. copy/pasted the readme program to `test.js`
2. ran it:

```
$ node test.js
module.js:440
    throw err;
    ^

Error: Cannot find module 'nlp-syllables'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\--\Projects\nlp-lyrics\test.js:2:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

env:

```
$ node -v
v6.1.0
```

using:

```
+-- nlp-syllables@0.0.2
+-- nlp_compromise@4.10.5
```

**Comment by factormystic** [comment]
The installed package.json says:

```
  "main": "builds/nlp-syllables.es5.js",
```

but there's no file on disk named that. The builds folder just has `nlp-syllables.js` and `nlp-syllables.min.js`.
